# Generated by Django 4.2.3 on 2023-07-20 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_submission_tries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='tries',
        ),
    ]
