# Generated by Django 4.2.3 on 2023-07-20 19:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0004_remove_submission_tries'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='time',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
