# Generated by Django 4.2.3 on 2023-07-20 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0005_submission_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
