# Generated by Django 4.2.3 on 2023-07-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0007_remove_question_lesson_question_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
